spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bulk?zeroDateTimeBehavior=convertToNull
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    maximum-pool-size: 10
  #    minimum-idle: 20
  #    max-lifetime: 598000
  #    write.idle-timeout: 300000
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    properties:
      hibernate:
        query:
          plan_cache_max_size: 256
          plan_parameter_metadata_max_size: 16
        default_batch_fetch_size: 30
        jdbc.time_zone: UTC
  kafka:
    bootstrap-servers: localhost:29092
  redis:
    host: localhost
    port: 6379
server:
  port: 50000